# Generated by Django 3.0.8 on 2020-08-12 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_delivery', '0002_auto_20200810_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='datePosted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default='Details not provided by Chef.'),
        ),
        migrations.AddField(
            model_name='food',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(),
        ),
    ]
