# Generated by Django 3.0.8 on 2020-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default-profile-pic.jpg', upload_to='profile_pics'),
        ),
    ]
