# Generated by Django 3.0.8 on 2020-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200816_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Tamil Nadu', 'Tamil Nadu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Manipur', 'Manipur'), ('Odisha', 'Odisha'), ('Uttarakhand', 'Uttarakhand'), ('Jharkhand', 'Jharkhand'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Kerala', 'Kerala'), ('Haryana', 'Haryana'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Meghalaya', 'Meghalaya'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Mizoram', 'Mizoram'), ('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Chhattisgarh', 'Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Puducherry', 'Puducherry'), ('Assam', 'Assam'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Nagaland', 'Nagaland'), ('Himachal Praddesh', 'Himachal Praddesh'), ('Bihar', 'Bihar'), ('Tripura', 'Tripura'), ('Chandigarh', 'Chandigarh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Gujarat', 'Gujarat'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab')], default='Your state here', max_length=120),
        ),
    ]
