# Generated by Django 3.1 on 2020-08-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200816_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Himachal Praddesh', 'Himachal Praddesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Manipur', 'Manipur'), ('Nagaland', 'Nagaland'), ('Telangana', 'Telangana'), ('Chandigarh', 'Chandigarh'), ('Odisha', 'Odisha'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Delhi', 'Delhi'), ('Maharashtra', 'Maharashtra'), ('Meghalaya', 'Meghalaya'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jharkhand', 'Jharkhand'), ('Uttarakhand', 'Uttarakhand'), ('Mizoram', 'Mizoram'), ('West Bengal', 'West Bengal'), ('Puducherry', 'Puducherry'), ('Rajasthan', 'Rajasthan'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Tamil Nadu', 'Tamil Nadu'), ('Tripura', 'Tripura'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala')], default='Your state here', max_length=120),
        ),
    ]
