# Generated by Django 3.1.4 on 2020-12-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200817_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='localityAddress',
            field=models.CharField(default='Your local address here', help_text='Enter your house number and the society name here', max_length=180),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Mizoram', 'Mizoram'), ('Haryana', 'Haryana'), ('Tamil Nadu', 'Tamil Nadu'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Telangana', 'Telangana'), ('Kerala', 'Kerala'), ('Assam', 'Assam'), ('Manipur', 'Manipur'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Meghalaya', 'Meghalaya'), ('Chandigarh', 'Chandigarh'), ('Tripura', 'Tripura'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Rajasthan', 'Rajasthan'), ('Odisha', 'Odisha'), ('Chhattisgarh', 'Chhattisgarh'), ('West Bengal', 'West Bengal'), ('Uttarakhand', 'Uttarakhand'), ('Maharashtra', 'Maharashtra'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Puducherry', 'Puducherry'), ('Nagaland', 'Nagaland'), ('Goa', 'Goa'), ('Himachal Praddesh', 'Himachal Praddesh'), ('Gujarat', 'Gujarat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Punjab', 'Punjab'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli')], default='Your state here', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default-profile-pic.jpg', upload_to='profile_pics'),
        ),
    ]
