# Generated by Django 3.1.4 on 2020-12-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_panel_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyvalue',
            old_name='consumption',
            new_name='Consumption',
        ),
        migrations.RenameField(
            model_name='dailyvalue',
            old_name='genActual',
            new_name='Solar Meter (Actual)',
        ),
        migrations.RenameField(
            model_name='dailyvalue',
            old_name='genCompany',
            new_name='Solar Meter (Company)',
        ),
    ]
